### ISSUE TITLE
Conflicts between django-html-emailer and commonmark

### ISSUE THREAD

**Issue by NeolithEra** [if-then-fund/django-html-emailer#3]
Hi, users are unable to run **_django-html-emailer_** due to dependency conflict with _**commonmark**_ package. As shown in the following full dependency graph of **_django-html-emailer_**, **_django-html-emailer_** requires _**commonmark >=0.8.0**_，while **_commonmarkextensions_** requires _**commonmark >=0.8.0,<=0.8.1**_.

According to pip’s _“first found wins”_ installation strategy, _**commonmark 0.9.1**_ is the actually installed version. However, _**commonmark 0.9.1**_ does not satisfy _**>=0.8.0,<=0.8.1**_.

### Dependency tree-----------
```
django-html-emailer - 0.0.8.1
| +- commonmark(install version:0.9.1 version range:>=0.8.0)
| | +- future(install version:0.18.2 version range:>=0.14.0)
| +- commonmarkextensions(install version:0.0.5 version range:>=0.0.5)
| | +- commonmark(install version:0.8.1 version range:>=0.8.0,<=0.8.1)
| | | +- future(install version:0.18.2 version range:*)
| +- pynliner(install version:0.8.0 version range:*)
| | +- beautifulsoup4 (install version:4.8.1 version range:>=4.4.1)
| | | +- soupsieve(install version:1.9.5 version range:>=1.2)
| | +- cssutils (install version:1.0.2 version range:>=0.9.7)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution

1.	Ask your upstream project _**commonmarkextensions**_ to loose the version range of **_commonmark_**.
2.	Fix your direct dependency to be _**commonmark >=0.8.0,<=0.8.1**_. I have checked this revision will not affect your downstream projects now.
3.	Remove your direct dependency _**commonmark**_, and use **_commonmark_** transitively introduced by _**commonmarkextensions**_.

@JoshData Which solution do you prefer, 1, 2or 3?
Please let me know your choice. I can submit a PR to solve this issue.

**Comment by JoshData** [comment]
Thanks! Have you checked if the libraries will work with commonmark 0.9.1? While we're here, we might want to update the version constraint to allow that both here and in commonmarkextensions (which I am also the author of).

**Comment by JoshData** [comment]
I think this is fixed via the upstream PR. Thanks and apologies for the delay!
